//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailBill
    {
        public int stt { get; set; }
        public int bID { get; set; }
        public int spID { get; set; }
        public string DVT { get; set; }
        public int Quantity { get; set; }
        public string Price { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
