//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kho
    {
        public int kID { get; set; }
        public int hdID { get; set; }
        public int spID { get; set; }
        public string DVT { get; set; }
        public int Quantity { get; set; }
        public System.DateTime MFG { get; set; }
        public System.DateTime EXP { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual HoatDong HoatDong { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
