//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.Bills = new HashSet<Bill>();
            this.TaiKhoans = new HashSet<TaiKhoan>();
        }
    
        public int nvID { get; set; }
        public string nvName { get; set; }
        public System.DateTime nvDOB { get; set; }
        public string nvIDNumber { get; set; }
        public string nvPhone { get; set; }
        public string nvAddress { get; set; }
        public int DayOn { get; set; }
        public int DayOff { get; set; }
        public string Salary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
        public static bool Compare_TenNhanVien(object o1, object o2)
        {
            if (string.Compare(o1.ToString(), o2.ToString()) > 0) return true;
            else return false;
        }
    }
}
